version: "3"

services:
  app:
    depends_on:
      - db
    build: 
      context: app/.
    env_file:
      - env/.env_app
    ports:
      - 5000:5000
    volumes:
      - .:/app
  db:
    build:
      context: db/.
    env_file:
      - env/.env-db
    ports:
      - 5432:5432
    volumes:
      - todo-data:/var/lib/postgres
    
volumes:
  todo-data:
